XCODE_USER_TEMPLATES_DIR=~/Library/Developer/Xcode/Templates/File\ Templates
XCODE_USER_SNIPPETS_DIR=~/Library/Developer/Xcode/UserData/CodeSnippets

TEMPLATES_DIR=Clean\ MVVM
SNIPPETS_DIR=Clean\ MVVM\ Snippets

install_templates:
	mkdir -p $(XCODE_USER_TEMPLATES_DIR)
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/$(TEMPLATES_DIR)
	cp -R $(TEMPLATES_DIR) $(XCODE_USER_TEMPLATES_DIR)

	mkdir -p $(XCODE_USER_SNIPPETS_DIR)
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/$(SNIPPETS_DIR)
	cp -r $(SNIPPETS_DIR)/* $(XCODE_USER_SNIPPETS_DIR)

uninstall_templates:
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/$(TEMPLATES_DIR) $(XCODE_USER_SNIPPETS_DIR)/*